### ISSUE TITLE
로고

### ISSUE THREAD

**Issue by kang0921ok** [kang0921ok/statistics_cloud#24]
프로젝트 : OCTOPUS

로고생성

**Comment by Haru922** [comment]
[Sample.pdf](https://github.com/kang0921ok/statistics_cloud/files/2431445/Sample.pdf)
[sample2.pdf](https://github.com/kang0921ok/statistics_cloud/files/2431446/sample2.pdf)
![octopus logo](https://user-images.githubusercontent.com/42909013/46256555-ce01ce80-c49b-11e8-91d1-0f03320f66db.png)
Octopus
